### PR TITLE
finshed lab 1

### PR DESCRIPTION
**Pull request by potatchipsxp**
I left in two variables that I wanted to show something im confused about but they dont use the same names as anything you have. If this confuses travis ill fix it.

### CODE REVIEW

**Comment by dhicks** [comment]
I don't see any commits by you in here

**Comment by dhicks** [comment]
I think there might be some GitHub settings causing complications.  Give me 10 minutes and then try submitting another pull request.

**Comment by potatchipsxp** [comment]
I cant tell by this thread, did this get resolved or should I try pulling again?

**Comment by dhicks** [comment]
Try submitting another pull request

**Pull request closed without merging**
